### ISSUE TITLE
Settings & Look

### ISSUE THREAD

**Issue by Chondremos** [messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll#1]
Hi,

your plugin works like a charm but there are two little things.
1. In the configuration view there is no option to enable or disable the plugin I think there should be a checkbox in the Mailbox View settings or?
2. Is it possible to add the total count of messages and the selected messages into the mailview middle bar like "n selected of n messages" instead of "Messages 1 to n of n"?

I use Roundcube V.1.1.4

**Comment by tpayen** [comment]
Hello,
Thank you for this return

To the first point, it should be the case. This is probably a bug, I look for a correction asap.

For the second, I would actually do it. But I have not had time.

**Comment by tpayen** [comment]
The settings bug is fixed in the new release v0.2

**Comment by Chondremos** [comment]
Hi,
the option now appear into the mail view settings - thanks - but the state will not saved. I activated once the force option in v0.1. With v0.2 I set the force flag to false and use the internal option but the plugin is always active and cant change. I tested it with FF, IE, Chrome (always clean temp / cache / cookie)

**Comment by tpayen** [comment]
This is how the settings work in Roundcube, the individual settings take over the global settings. But when you check/uncheck and save the option it must change for you. If this is not the case, can you look in the errors log file, if there something wrong ?

**Comment by Chondremos** [comment]
Hi,
the errorlog is empty and roundcube say "Successfully saved". But when I reload the setting-page the plugin is active again.

I also deleted the preferences in my database so that rc should use the defaults but the plugin is active (config say: off)

This is my POST by unchecking the box:

> _action   save-prefs
> _framed   1
> _mail_pagesize    50
> _mdn_requests 0
> _newmail_notifier_basic   1
> _newmail_notifier_desktop 1
> _newmail_notifier_desktop...  10
> _preview_pane 1
> _preview_pane_mark_read   0
> _section  mailbox
> _task settings
> _token    

If I check the box my POST contain:

> _pref_use_infinite_scroll 1

**Comment by tpayen** [comment]
Your POST is ok, so I don't understand why this doesn't work

**Comment by Chondremos** [comment]
After all I have changed my computer and now it works - strange. Sorry for this...

Edit: I have changed the setting with another PC and after that, the on/off function get worked on the old computer too. hm..

**Comment by mckaygerhard** [comment]
the problem its the cache browser and cache server, if both are set some setting will reamin and override the others.. will happend only on too recent version of firefox, chrome, but specially many many in some poor OS such mocosoft guindows

if u before go to the other computer clear cache in browser and server the configuration process work in the older computer...

for the second about amount of messages, i made a request for that in the issues.. and in future will work with (but not  priority)

**Comment by filhocf** [comment]
Hi

I believe that is possible to close this bug. I tried to find the related errors without find anything.

And congratulations by your work.

**Comment by mckaygerhard** [comment]
you cannot close this bug, this problem as i posted previously, was happened due cache browser, now with newer firefox the problem can happened on certanin clients.. it-s a pain
