### ISSUE TITLE
enable also for mail body and preview panel

### ISSUE THREAD

**Issue by mckaygerhard** [messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll#3]
its more usefull thsi feature plugin in the message body

and much more in preview panel, that have some iframes and many other parts

in the message, the bars are ugly and this plugin seems does not work!

**Comment by tpayen** [comment]
I don't really understand the request ?
This plugin enable an infinite scroll in the message list to load more messages from the server, the scroll in the message body already work in native Roundcube and I don't see what more this plugin can do

**Comment by mckaygerhard** [comment]
could provide same functionallity to the message scroll also? that's all!

(also in preview panel message scroll  too)
