### ISSUE TITLE
Uncaught ReferenceError: rcube_list_widget is not defined

### ISSUE THREAD

**Issue by vitlav** [messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll#7]
I got error in browser console:
Uncaught ReferenceError: rcube_list_widget is not defined
    at infinitescroll.js?s=1499959988:73

There is possible missed variable:
if (rcmail
    && (rcmail.env.task == 'mail' || rcmail.env.task == 'addressbook')
    && rcube_list_widget) {
  /**

**Comment by tpayen** [comment]
Yes I also have this error sometimes but it's not clear to me, as if the if didn't do the job
