### ISSUE TITLE
Elastic skin - not working with infinitescroll plugin

### ISSUE THREAD

**Issue by zden2ksobotka** [messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll#9]
Hello, new Elastic skin does not work properly with plugin "infinitescroll", while other default skins works. (tested in Roundcube 1.4-rc1)

https://github.com/roundcube/roundcubemail/issues/6700

**Comment by CoolMcFly81** [comment]
Just have a look at my pull-request :-)
[Pull Request #11](https://github.com/messagerie-melanie2/Roundcube-Plugin-Infinite-Scroll/pull/11)

**Comment by tpayen** [comment]
Thanks to @CoolMcFly81 this issue is closed in v0.3
